### ISSUE TITLE
Remove unnecessary locks in the master code

### ISSUE THREAD

**Issue by eigenein** [eigenein/cloudy#44]

**Comment by igor-kalashnikov** [comment]
Could you please clarify which locks you mean?

**Comment by eigenein** [comment]
https://github.com/eigenein/cloudy/blob/master/Cloudy/Computing/Nodes/AbstractMasterNode.cs

Надо проверить, все ли операторы `lock` нужны в коде. Мне, когда заводил ишшус, показалось, что некоторые там лишние.
