### ISSUE TITLE
MPI_Allgather

### ISSUE THREAD

**Issue by eigenein** [eigenein/cloudy#48]
http://www.mcs.anl.gov/research/projects/mpi/www/www3/MPI_Allgather.html

**Comment by igor-kalashnikov** [comment]
Нужно ли? Это частный случай Gather, так ведь?

**Comment by eigenein** [comment]
Нет, это не частный случай.

**Comment by igor-kalashnikov** [comment]
Эээ, да, я уже давно понял ) Забыл о комменте.
