### ISSUE TITLE
MPI_Gather

### ISSUE THREAD

**Issue by eigenein** [eigenein/cloudy#51]

**Comment by eigenein** [comment]
`Environment.Gather(IEnumerable<TRank> recipients)` - запрос у реципиентов
`Environment.Gather(TValue value, IEnumerable<TRank> recipients)` - запрос у реципиентов + своё значение
`Environment.Gather(T value)` - только предоставление значения другим

В идеале ещё бы сделать аналоги с фильтрацией по `sender`у, но нам сейчас принципиально количество различных операций, так что, потом.

Реализуется аналогично `Environment.Send`. Заведи два новых `EnvironmentOperationType` - `GatherRequest` и `GatherResponse`, `EnvironmentOperationValue` ничего нести не будет. В вызывающем - ожидаешь всех ответов (`GatherResponse`) и собираешь в один `Collection`, в тех, что только предоставляют значения - ждёшь `GatherRequest` и отвечаешь с `GatherResponse`.

**Comment by igor-kalashnikov** [comment]
В оригинале Gather собирает массивы данных в один. Ты предлагаешь здесь собирать именно значения?

**Comment by eigenein** [comment]
Fixed.
