### ISSUE TITLE
MPI_Scatter

### ISSUE THREAD

**Issue by eigenein** [eigenein/cloudy#52]
http://www.mcs.anl.gov/research/projects/mpi/www/www3/MPI_Scatter.html

**Comment by igor-kalashnikov** [comment]
Implemented.

**Comment by eigenein** [comment]
Переоткрыто в связи с https://github.com/eigenein/cloudy/commit/449931612388985d926f245f3fb93c97f090e2b7#commitcomment-1271418

**Comment by igor-kalashnikov** [comment]
Close cause of #64.
