### ISSUE TITLE
Different solution for examples

### ISSUE THREAD

**Issue by igor-kalashnikov** [eigenein/cloudy#62]
There are many example projects in solution. Maybe it would be better to join its or separate to the new solution.

**Comment by eigenein** [comment]
Не вижу пользы. А вот вреда:
- Join'ить толком не получится: это же отдельные ехешники + разделяемые между ними сборки
- Разделять в solution'ы - теряешь IntelliSense

**Comment by igor-kalashnikov** [comment]
Ок.
